name: e3rescue

channels:
  - conda-forge

dependencies:
  - python >= 3.7
  - pip
  - matplotlib
  - numpy
  - pandas
  - jupyterlab
  - scipy
  - xlrd
  - pvlib-python          # Package from Sandia NL for solar resource related functions
  - xlwings               # package for excel reading and writing
  
  - pip:
    - tensorflow          # Machine learning
