name: e3rescue

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - jupyterlab
  - scipy
  - xlrd
  
  - pip:
    - tensorflow                        # Machine learning
